<?php
return [
    'DEBUGGER_EMAIL' => env('DEBUGGER_EMAIL', false),
    'DEBUGGER_MAIL_HOST' => env('DEBUGGER_MAIL_HOST', false),
    'DEBUGGER_MAIL_PORT' => env('DEBUGGER_MAIL_PORT', false),
    'DEBUGGER_MAIL_USERNAME' => env('DEBUGGER_MAIL_USERNAME', false),
    'DEBUGGER_MAIL_PASSWORD' => env('DEBUGGER_MAIL_PASSWORD', false),
    'DEBUGGER_MAIL_ENCRYPTION' => env('DEBUGGER_MAIL_ENCRYPTION', false),
];